default_stages: [commit]
default_language_version:
  python: python3.9
repos:
  - repo: local
    hooks:
      - id: html-notebooks
        name: html-notebooks
        entry: ./scripts/update-html.sh
        language: system
        always_run: true
        files: \.ipynb$
