name: Eleventy Build

defaults:
  run:
    working-directory: ./web

on:
  push:
    branches:
      - master

jobs:
  deploy-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.9'
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install Dependencies
        run: poetry install
      - name: Prepare HTML notebooks
        run: ./scripts/update-html.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-notebooks
          path: ./docs

  deploy-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
        working-directory: ./web
      - name: Download notebook atrifacts
        uses: actions/download-artifact@v3
        with:
          name: html-notebooks
          path: ./docs
      - run: npm run build
        working-directory: ./web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES }}
          publish_dir: ./docs
