name: Eleventy Build

defaults:
  run:
    working-directory: ./web

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES }}
          publish_dir: ./dist
